include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: true

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore
    argument_type_not_assignable: ignore
